setono_sylius_criteo_admin_account:
    resource: |
        section: admin
        alias: setono_sylius_criteo.account
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: setono_sylius_criteo_admin_account
        vars:
            all:
                subheader: setono_sylius_criteo.ui.account
            index:
                icon: 'file image outline'
    type: sylius.resource
