sylius_grid:
    grids:
        setono_sylius_criteo_admin_account:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_criteo.model.account.class%"
            fields:
                accountId:
                    type: string
                    label: setono_sylius_criteo.ui.account_id
                channel:
                    type: string
                    label: setono_sylius_criteo.ui.channel
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
