Setono\SyliusCriteoPlugin\Model\CriteoConfig:
    constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
          fields: [accountId]
          message: 'setono_sylius_analytics.criteo_config.account_id.unique'
          groups: ['setono']
    properties:
        accountId:
        - NotBlank:
              message: 'setono_sylius_analytics.criteo_config.account_id.not_blank'
              groups: ['setono']
        - Length:
              min: 2
              max: 250
              minMessage: 'setono_sylius_analytics.criteo_config.account_id.min_length'
              maxMessage: 'setono_sylius_analytics.criteo_config.account_id.max_length'
              groups: ['setono']
